cc_library(
  name = "lib2",
  srcs = ["lib2.cc"],
  hdrs = ["lib2.h"],
  deps = [],
  visibility = ["//visibility:public"],
)

cc_binary(
  name = "bin2",
  srcs = ["bin2.cc"],
  deps = [],
  visibility = ["//visibility:public"],
)